steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/PhuocVinh308/APIPOS', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/apipos', '.']
    timeout: '1600s'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['--', 'push', 'gcr.io/$PROJECT_ID/apipos']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'apipos'
      - '--image=gcr.io/$PROJECT_ID/apipos'
      - '--platform=managed'
      - '--region=your-region' # Thay your-region bằng khu vực mong muốn, ví dụ: us-central1
      - '--allow-unauthenticated' # Cho phép truy cập không xác thực
    timeout: '1600s'

timeout: '2000s' # Thời gian tối đa cho toàn bộ quy trình Cloud Build
